# Dependabot will run on day 4 of each month at 02:18 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "18 2 4 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "18 2 4 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
    directories:
      - "**/*"
